#ifndef BINDINGS_PYTHON_ODE_EULER_BACKWARD_BINDINGS_HPP_
#define BINDINGS_PYTHON_ODE_EULER_BACKWARD_BINDINGS_HPP_

#include <pybind11/pybind11.h>

void BindEulerBackward(pybind11::module_& m);

#endif  // BINDINGS_PYTHON_ODE_EULER_BACKWARD_BINDINGS_HPP_
